/* Authentication */
export const AUTH_USER = "AUTH_USER";
export const UNAUTH_USER = "UNAUTH_USER";
export const LOGIN_AUTH_ERROR = "LOGIN_AUTH_ERROR";
export const REGISTRATION_AUTH_ERROR = "REGISTRATION_AUTH_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

/* Post */
/* Brand Loyalty Programs */
export const REQUEST_POSTS_LIST = "REQUEST_POSTS_LIST";
export const RECEIVE_POSTS_LIST = "RECEIVE_POSTS_LIST";
export const REQUEST_MORE_POSTS = "REQUEST_MORE_POSTS";
export const RECEIVE_MORE_POSTS = "RECEIVE_MORE_POSTS";
export const CHANGE_POSTS_PAGE = "CHANGE_POSTS_PAGE";
export const SET_PAGE = 'SET_PAGE';

/* Users List */
export const REQUEST_USERS_LIST = "REQUEST_USERS_LIST";
export const RECEIVE_USERS_LIST = "RECEIVE_USERS_LIST";
export const FETCH_USERS_LIST_FAIL = "FETCH_USERS_LIST_FAIL";
export const REQUEST_MORE_USERS = "REQUEST_MORE_USERS";
export const RECEIVE_MORE_USERS = "RECEIVE_MORE_USERS";
export const FETCH_MORE_USERS_FAIL = "FETCH_MORE_USERS_FAIL";
export const CHANGE_USERS_PAGE = "CHANGE_USERS_PAGE";
